"""Generate the worked example and expand the introductory gear-train lesson."""
from build_portal import ROOT, BASE, head, footer
import json
import re

PT = '''
<p class="lead">Uma animação pode parecer coerente mesmo quando a entrada, a saída ou o elemento fixo foram escolhidos de forma diferente da conta no papel. Neste exemplo, o mesmo conjunto de dentes será analisado em três configurações. O objetivo é obter resultados que você possa conferir por substituição, antes de usar uma ferramenta de simulação.</p>
<nav class="toc" aria-label="Neste artigo"><strong>Neste artigo</strong><a href="#dados">1. Dados e hipóteses</a><a href="#equacao">2. Uma equação para os três casos</a><a href="#casos">3. Resultados calculados</a><a href="#conferencia">4. Como conferir na simulação</a><a href="#erros">5. Erros de interpretação</a><a href="#exercicio">6. Exercício com resposta</a></nav>
<h2 id="dados">1. Dados e hipóteses</h2>
<p>Considere uma planetária simples com uma engrenagem solar S de 24 dentes, uma coroa interna R de 72 dentes e satélites P de 24 dentes, sustentados por um porta-satélites C. Adotamos engrenagens cilíndricas de dentes retos, mesmo módulo e geometria de referência sem correção de perfil. A análise é cinemática: não calcula tensões, folgas, atrito ou capacidade de carga.</p>
<p>A primeira verificação é geométrica. Para esse arranjo, os diâmetros primitivos exigem N<sub>R</sub> = N<sub>S</sub> + 2N<sub>P</sub>. Portanto, 72 = 24 + 2 × 24. Se o módulo escolhido for 2 mm, os diâmetros primitivos serão 48 mm, 144 mm e 48 mm, respectivamente. A distância do eixo central ao eixo de um satélite será (48 + 48)/2 = 48 mm; pelo contato interno, também será (144 − 48)/2 = 48 mm.</p>
<p>Essa igualdade é necessária, mas não encerra o projeto. Montar vários satélites requer verificar espaçamento, fase dos dentes, interferência e condições de fabricação. Aqui, queremos apenas um conjunto de dados coerente para estudar velocidades.</p>
<h2 id="equacao">2. Uma equação para os três casos</h2>
<p>Escolha um sentido positivo comum para todos os eixos, observados do mesmo lado. As rotações n serão dadas em rpm. Para relacionar o sol e a coroa, subtraia de ambos a rotação do braço:</p>
<p class="formula">(n<sub>S</sub> − n<sub>C</sub>) / (n<sub>R</sub> − n<sub>C</sub>) = −N<sub>R</sub> / N<sub>S</sub> = −3</p>
<p>O sinal negativo vem do trem observado com o braço parado: um contato externo entre sol e satélite inverte o sentido; o contato interno entre satélite e coroa não o inverte. Para evitar divisão por zero quando dois elementos giram juntos, use a forma equivalente, sem denominador:</p>
<p class="formula">24n<sub>S</sub> + 72n<sub>R</sub> − 96n<sub>C</sub> = 0<br>n<sub>C</sub> = (24n<sub>S</sub> + 72n<sub>R</sub>) / 96</p>
<p>Há três rotações e uma relação independente. É preciso impor duas condições para determinar a terceira: por exemplo, a rotação da entrada e a imobilização de outro elemento. Informar apenas “entrada de 1 200 rpm” não define o funcionamento.</p>
<h2 id="casos">3. Resultados calculados</h2>
<h3>Coroa fixa: redução de 4:1</h3>
<p>Faça n<sub>R</sub> = 0 e n<sub>S</sub> = 1 200 rpm. A rotação do braço é (24 × 1 200)/96 = <strong>300 rpm</strong>. Entrada e saída têm o mesmo sentido. Definindo a relação como i = n<sub>entrada</sub>/n<sub>saída</sub>, temos i = 1 200/300 = 4.</p>
<p>Confira o resultado na equação original: (1 200 − 300)/(0 − 300) = 900/(−300) = −3. A velocidade relativa do sol ao braço é 900 rpm, mas a velocidade absoluta do sol continua sendo 1 200 rpm. Confundir essas duas leituras é uma fonte frequente de erro.</p>
<h3>Sol fixo: redução de 4:3</h3>
<p>Agora imponha n<sub>S</sub> = 0 e use a coroa como entrada a n<sub>R</sub> = 1 200 rpm. O braço gira a (72 × 1 200)/96 = <strong>900 rpm</strong>. A relação entrada/saída é 4/3, aproximadamente 1,333. Os dentes não mudaram; a troca do elemento fixo e da entrada mudou a redução.</p>
<h3>Braço fixo: inversão de sentido</h3>
<p>Faça n<sub>C</sub> = 0 e n<sub>S</sub> = 1 200 rpm. A equação fica 24 × 1 200 + 72n<sub>R</sub> = 0. Logo, n<sub>R</sub> = <strong>−400 rpm</strong>. A coroa gira em sentido oposto ao sol. A relação com sinal é −3; a magnitude da redução é 3:1.</p>
<div class="table-scroll"><table><caption>Comparação das três configurações, em rpm</caption><thead><tr><th scope="col">Elemento fixo</th><th scope="col">Sol S</th><th scope="col">Coroa R</th><th scope="col">Braço C</th><th scope="col">Entrada / saída</th></tr></thead><tbody><tr><th scope="row">Coroa</th><td>1 200</td><td>0</td><td>300</td><td>4</td></tr><tr><th scope="row">Sol</th><td>0</td><td>1 200</td><td>900</td><td>4/3</td></tr><tr><th scope="row">Braço</th><td>1 200</td><td>−400</td><td>0</td><td>−3</td></tr></tbody></table></div>
<h2 id="conferencia">4. Como conferir na simulação</h2>
<p>Abra o <a href="https://barbudenge.github.io/engrenarium/pt-br/">Engrenarium Web</a> e use um arranjo equivalente, com os mesmos dentes e vínculos. Compare as rotações calculadas, não apenas a impressão visual da animação. Se os nomes ou a orientação do desenho forem diferentes, primeiro associe cada elemento ao sol, à coroa e ao braço deste exemplo.</p>
<ol><li>Registre qual elemento recebe a rotação e qual está fixo.</li><li>Anote a convenção de sinal e a unidade mostrada. Para converter rpm em rad/s, multiplique por 2π/60.</li><li>Substitua os três resultados na expressão 24n<sub>S</sub> + 72n<sub>R</sub> − 96n<sub>C</sub>. O resultado deve ser zero, salvo arredondamentos.</li><li>Repita a análise mudando somente os vínculos, mantendo os números de dentes.</li></ol>
<p>Esse procedimento é uma conferência independente, não um relato de ensaio ou de validação de uma versão específica do programa. Um pequeno resíduo após usar números arredondados deve ser comparado à precisão dos valores exibidos; um erro grande pede revisão das entradas e dos vínculos.</p>
<h2 id="erros">5. O que esse cálculo não permite concluir</h2>
<p><strong>Redução não é eficiência.</strong> Uma relação 4:1 não informa o rendimento. No modelo ideal, com coroa fixa e sem perdas, a magnitude do torque no braço pode ser quatro vezes a do torque de entrada no sol. Um conjunto real exige considerar perdas e resistência dos componentes; a carcaça também recebe o torque de reação do elemento fixo.</p>
<p><strong>Satélite girando não significa braço girando.</strong> O satélite pode girar sobre o próprio eixo enquanto seu centro acompanha o braço. Com o braço fixo, os centros dos satélites param, mas seus corpos ainda podem girar.</p>
<p><strong>Trocar a definição da relação inverte o número.</strong> Se a saída é 300 rpm e a entrada 1 200 rpm, saída/entrada vale 0,25 e entrada/saída vale 4. Ambos são compatíveis, desde que a definição acompanhe o resultado.</p>
<h2 id="exercicio">6. Exercício: duas entradas em movimento</h2>
<p>Mantenha os dentes e imponha n<sub>S</sub> = 600 rpm e n<sub>R</sub> = −200 rpm. Qual será a rotação do braço? Antes de abrir a resposta, observe que as contribuições do sol e da coroa possuem pesos diferentes na equação.</p>
<details><summary>Ver cálculo e interpretação</summary><p>n<sub>C</sub> = (24 × 600 + 72 × (−200))/96 = 0 rpm. O braço fica parado mesmo com sol e coroa em movimento. As contribuições se cancelam. Isso confirma que o braço não acompanha necessariamente o elemento de maior rotação em módulo.</p></details>
<h2>Base conceitual e próximas leituras</h2><p>Os números deste guia formam um exemplo didático calculado para esta página. A dedução geral está em <a href="engrenagens-planetarias.html">Engrenagens planetárias: caso geral e valor do trem</a>; os vínculos de eixo são discutidos em <a href="trens-engrenagens-simples-compostos.html">Trens simples e compostos</a>. Para avançar além da planetária simples, veja <a href="planetarias-compostas-diferenciais.html">Planetárias compostas e diferenciais</a>.</p>
'''

EN = '''
<p class="lead">An animation may look plausible even when its input, output or fixed member differs from the assumptions used on paper. This worked example analyses the same tooth counts in three configurations. The goal is to obtain results you can check by substitution before using a simulation tool.</p>
<nav class="toc" aria-label="In this article"><strong>In this article</strong><a href="#dados">1. Inputs and assumptions</a><a href="#equacao">2. One equation for three cases</a><a href="#casos">3. Calculated results</a><a href="#conferencia">4. Checking a simulation</a><a href="#erros">5. Interpretation mistakes</a><a href="#exercicio">6. Exercise with solution</a></nav>
<h2 id="dados">1. Inputs and assumptions</h2>
<p>Consider a simple planetary train with a 24-tooth sun S, a 72-tooth internal ring R and 24-tooth planets P supported by carrier C. Assume spur gears of equal module with reference geometry and no profile shift. This is a kinematic analysis: it does not calculate stress, backlash, friction or load capacity.</p>
<p>Start with the geometry. The pitch diameters in this arrangement require N<sub>R</sub> = N<sub>S</sub> + 2N<sub>P</sub>. Here, 72 = 24 + 2 × 24. With a module of 2 mm, the sun, ring and planet pitch diameters are 48 mm, 144 mm and 48 mm. The distance from the central axis to a planet axis is (48 + 48)/2 = 48 mm. The internal mesh gives the same distance: (144 − 48)/2 = 48 mm.</p>
<p>This equality is necessary but does not complete the design. Multiple planets require checks for spacing, tooth phasing, interference and manufacturing conditions. Here we only need a coherent input set for studying rotational speeds.</p>
<h2 id="equacao">2. One equation for three cases</h2>
<p>Choose the same positive direction for every axis, viewed from the same side. Speeds n are in rpm. To relate sun and ring motion, subtract the carrier speed from each:</p>
<p class="formula">(n<sub>S</sub> − n<sub>C</sub>) / (n<sub>R</sub> − n<sub>C</sub>) = −N<sub>R</sub> / N<sub>S</sub> = −3</p>
<p>The negative sign comes from the train observed with the carrier stationary: the external sun–planet mesh reverses direction, whereas the internal planet–ring mesh does not. To avoid division by zero when members rotate together, use the equivalent form without a denominator:</p>
<p class="formula">24n<sub>S</sub> + 72n<sub>R</sub> − 96n<sub>C</sub> = 0<br>n<sub>C</sub> = (24n<sub>S</sub> + 72n<sub>R</sub>) / 96</p>
<p>There are three speeds and one independent relation. Two conditions must be specified to determine the third speed: for example, an input speed and a stationary member. Saying only “input at 1,200 rpm” does not define the operating condition.</p>
<h2 id="casos">3. Calculated results</h2>
<h3>Fixed ring: a 4:1 reduction</h3>
<p>Set n<sub>R</sub> = 0 and n<sub>S</sub> = 1,200 rpm. The carrier speed is (24 × 1,200)/96 = <strong>300 rpm</strong>. Input and output rotate in the same direction. Defining the ratio as i = n<sub>input</sub>/n<sub>output</sub> gives i = 1,200/300 = 4.</p>
<p>Substitute into the original equation: (1,200 − 300)/(0 − 300) = 900/(−300) = −3. The sun speed relative to the carrier is 900 rpm, but its absolute speed remains 1,200 rpm. Mixing these two measurements is a common source of errors.</p>
<h3>Fixed sun: a 4:3 reduction</h3>
<p>Now set n<sub>S</sub> = 0 and use the ring as the input at n<sub>R</sub> = 1,200 rpm. The carrier rotates at (72 × 1,200)/96 = <strong>900 rpm</strong>. The input/output ratio is 4/3, approximately 1.333. No tooth counts changed; choosing a different fixed member and input changed the reduction.</p>
<h3>Fixed carrier: reversed rotation</h3>
<p>Set n<sub>C</sub> = 0 and n<sub>S</sub> = 1,200 rpm. The equation becomes 24 × 1,200 + 72n<sub>R</sub> = 0, giving n<sub>R</sub> = <strong>−400 rpm</strong>. The ring rotates opposite to the sun. The signed ratio is −3; the reduction magnitude is 3:1.</p>
<div class="table-scroll"><table><caption>Comparison of the three configurations, in rpm</caption><thead><tr><th scope="col">Fixed member</th><th scope="col">Sun S</th><th scope="col">Ring R</th><th scope="col">Carrier C</th><th scope="col">Input / output</th></tr></thead><tbody><tr><th scope="row">Ring</th><td>1,200</td><td>0</td><td>300</td><td>4</td></tr><tr><th scope="row">Sun</th><td>0</td><td>1,200</td><td>900</td><td>4/3</td></tr><tr><th scope="row">Carrier</th><td>1,200</td><td>−400</td><td>0</td><td>−3</td></tr></tbody></table></div>
<h2 id="conferencia">4. Checking a simulation</h2>
<p>Open <a href="https://barbudenge.github.io/engrenarium/">Engrenarium Web</a> and use an equivalent arrangement with the same teeth and constraints. Compare the calculated speeds rather than just the appearance of the animation. If labels or viewing directions differ, first identify which members correspond to this example's sun, ring and carrier.</p>
<ol><li>Record the driven member and the fixed member.</li><li>Check the sign convention and displayed units. To convert rpm to rad/s, multiply by 2π/60.</li><li>Substitute all three speeds into 24n<sub>S</sub> + 72n<sub>R</sub> − 96n<sub>C</sub>. The result should be zero, apart from rounding.</li><li>Repeat the analysis with different constraints while keeping the tooth counts unchanged.</li></ol>
<p>This is an independent checking procedure, not a report of a physical experiment or validation of a particular software release. Compare any small residual with the precision of the displayed values. A large discrepancy calls for checking inputs and constraints.</p>
<h2 id="erros">5. What the calculation does not establish</h2>
<p><strong>Reduction is not efficiency.</strong> A 4:1 ratio does not specify efficiency. In the ideal fixed-ring case, neglecting losses, carrier torque magnitude can be four times the sun input torque. Real hardware requires loss and component-strength calculations; the housing also carries the reaction torque of the fixed member.</p>
<p><strong>Planet rotation is not carrier rotation.</strong> A planet can spin about its own axis while its centre travels with the carrier. With the carrier fixed, planet centres stop moving, but the planets themselves can still spin.</p>
<p><strong>Reversing the ratio definition inverts the number.</strong> If output speed is 300 rpm and input speed is 1,200 rpm, output/input is 0.25 and input/output is 4. Both descriptions agree when the definition is stated.</p>
<h2 id="exercicio">6. Exercise: two moving inputs</h2>
<p>Keep the tooth counts and impose n<sub>S</sub> = 600 rpm and n<sub>R</sub> = −200 rpm. What is the carrier speed? Before opening the solution, note that sun and ring contributions have different weights in the equation.</p>
<details><summary>Show calculation and interpretation</summary><p>n<sub>C</sub> = (24 × 600 + 72 × (−200))/96 = 0 rpm. The carrier remains stationary even though the sun and ring are moving. Their contributions cancel. The carrier does not necessarily follow the member with the largest speed magnitude.</p></details>
<h2>Conceptual basis and further reading</h2><p>The numbers in this guide form an illustrative example calculated for this page. See the general derivation in <a href="engrenagens-planetarias.html">Planetary gears: general case and train value</a> and shaft constraints in <a href="trens-engrenagens-simples-compostos.html">Simple and compound gear trains</a>. To go beyond a simple planetary set, continue with <a href="planetarias-compostas-diferenciais.html">Compound planetary trains and differentials</a>.</p>
'''

EXAMPLES = [
'''<h2 id="exemplo-resolvido">Exemplo resolvido: duas reduções de 3:1</h2><p>Considere quatro engrenagens externas: A com 20 dentes aciona B com 60; B e C estão rigidamente presas ao mesmo eixo; C tem 18 dentes e aciona D com 54. A gira a +900 rpm. O sinal positivo é definido observando todos os eixos do mesmo lado.</p><p>A primeira malha fornece n<sub>B</sub> = −900 × 20/60 = −300 rpm. Como B e C são solidárias, n<sub>C</sub> = −300 rpm. A segunda malha fornece n<sub>D</sub> = −(−300) × 18/54 = +100 rpm. A saída gira no mesmo sentido da entrada e a redução total é 900/100 = 9:1.</p><p>Não multiplique 60/18 como se B e C engrenassem: elas compartilham a rotação, não uma relação de contato. Os números de dentes dessas duas engrenagens podem ser diferentes sem alterar a igualdade de velocidades no eixo comum.</p><h3>O que muda se o trem for simples?</h3><p>Agora use apenas A = 20, B = 60 e D = 54, cada uma em seu eixo, com A acionando B e B acionando D. A saída será (−20/60) × (−60/54) × 900 = +333,33 rpm. Os 60 dentes da intermediária cancelam no produto. A redução é 54/20 = 2,7:1. O resultado é diferente porque o caminho de transmissão mudou, embora algumas engrenagens tenham os mesmos dentes.</p><h3>Uma verificação independente</h3><p>Se todos os pares do primeiro exemplo tiverem módulo 2 mm e não houver correção de perfil, a distância entre os eixos de A e B será 2(20 + 60)/2 = 80 mm. Entre C e D será 2(18 + 54)/2 = 72 mm. Essa conferência de geometria complementa a de velocidades, mas não verifica resistência, interferência ou viabilidade da carcaça.</p><p>Para praticar, mantenha a montagem composta e troque D por uma engrenagem de 36 dentes. A saída passa a +150 rpm e a redução a 6:1. Se você obteve −150 rpm, reveja as duas inversões de sentido. Para continuar, use o <a href="conferir-resultados-planetaria.html">guia de conferência de planetárias</a> e observe o que muda quando um eixo passa a se mover com o braço.</p>''',
'''<h2 id="exemplo-resolvido">Worked example: two 3:1 reductions</h2><p>Consider four external gears: A has 20 teeth and drives B with 60 teeth; B and C are rigidly attached to the same shaft; C has 18 teeth and drives D with 54. A rotates at +900 rpm. Define the positive direction by viewing every shaft from the same side.</p><p>The first mesh gives n<sub>B</sub> = −900 × 20/60 = −300 rpm. Because B and C share a shaft, n<sub>C</sub> = −300 rpm. The second mesh gives n<sub>D</sub> = −(−300) × 18/54 = +100 rpm. Output rotates in the same direction as input, and the total reduction is 900/100 = 9:1.</p><p>Do not multiply by 60/18 as though B and C were meshing: they share a speed, not a mesh ratio. Their tooth counts can differ without changing the equal-speed constraint on their common shaft.</p><h3>What changes in a simple train?</h3><p>Now use only A = 20, B = 60 and D = 54, each on its own shaft, with A driving B and B driving D. Output speed is (−20/60) × (−60/54) × 900 = +333.33 rpm. The intermediate gear's 60 teeth cancel from the product. The reduction is 54/20 = 2.7:1. The result differs because the transmission path changed, even though some tooth counts stayed the same.</p><h3>An independent check</h3><p>If every pair in the first example has module 2 mm and no profile shift, the A–B centre distance is 2(20 + 60)/2 = 80 mm. The C–D centre distance is 2(18 + 54)/2 = 72 mm. This geometric check complements the speed calculation but does not check strength, interference or housing feasibility.</p><p>For practice, keep the compound arrangement and replace D with a 36-tooth gear. Output becomes +150 rpm and the reduction becomes 6:1. If you obtained −150 rpm, check the two direction reversals. Continue with the <a href="conferir-resultados-planetaria.html">planetary result-checking guide</a> to see what changes when an axis travels with a carrier.</p>'''
]

for pt, body in [(True, PT), (False, EN)]:
    root = '/pt-br/' if pt else '/'
    slug = 'artigos/conferir-resultados-planetaria.html'
    title = 'Como conferir resultados de uma planetária: três casos resolvidos' if pt else 'How to check planetary gear results: three worked cases'
    description = 'Sol de 24 dentes e coroa de 72: calcule três configurações, confira os sinais e resolva um exercício com duas entradas.' if pt else 'A 24-tooth sun and 72-tooth ring: calculate three configurations, check signs and solve an exercise with two inputs.'
    schema = {'@context':'https://schema.org','@type':'Article','headline':title,'description':description,'datePublished':'2026-09-21','dateModified':'2026-09-21','author':{'@type':'Organization','name':'Barbudenge','url':BASE+root+'sobre.html'},'inLanguage':'pt-BR' if pt else 'en','mainEntityOfPage':BASE+root+slug}
    text = head(title, description, root+slug, ('/' if pt else '/pt-br/')+slug, pt, schema)
    text = text.replace('property="og:type" content="website"','property="og:type" content="article"')
    text += f'<main id="main" class="wrap"><article class="reading"><p><a href="{root}artigos/">← {"Todos os artigos" if pt else "All articles"}</a></p><span class="eyebrow">{"Caderno de cálculo · Planetárias" if pt else "Calculation notebook · Planetary gears"}</span><h1>{title}</h1><p class="meta">Barbudenge · <time datetime="2026-09-21">2026-09-21</time> · {"Exemplo didático" if pt else "Worked example"}</p>'+body+'</article></main>'+footer(pt)
    (ROOT / root.strip('/') / slug).write_text(text,encoding='utf-8')
    lesson = ROOT / root.strip('/') / 'artigos/trens-engrenagens-simples-compostos.html'
    text = lesson.read_text(encoding='utf-8')
    if 'id="exemplo-resolvido"' not in text:
        text = text.replace('  </article>', EXAMPLES[0 if pt else 1]+'\n  </article>',1)
        text = text.replace('"dateModified": "2026-07-06"','"dateModified": "2026-09-21"')
        text = text.replace('<time datetime="2026-07-06">6 de julho de 2026</time>','<time datetime="2026-09-21">21 de setembro de 2026</time>')
        text = text.replace('<time datetime="2026-07-06">July 6, 2026</time>','<time datetime="2026-09-21">September 21, 2026</time>')
        lesson.write_text(text,encoding='utf-8')
